# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='username',
            field=models.CharField(default='user', max_length=50),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='senha',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='sexo',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('N\xe3o-declarado', 'N\xe3o-declarado')], max_length=20),
        ),
    ]
