# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('matricula', models.CharField(max_length=128)),
                ('senha', models.CharField(max_length=128)),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('N\xe3o-declarado', 'N\xe3o-declarado')], default='N\xe3o-declarado', max_length=20)),
                ('periodo', models.CharField(choices=[('2008.1', '08.1'), ('2009.1', '09.1'), ('2010.1', '10.1'), ('2011.1', '11.1'), ('2012.1', '12.1'), ('2013.1', '13.1'), ('2014.1', '14.1'), ('2015.1', '15.1'), ('2016.1', '16.1')], max_length=20)),
            ],
        ),
    ]
